### PR TITLE
cerebro image fit inside the screen

### PR DESCRIPTION
**Pull request by samagragupta**

### CODE REVIEW

**Comment by anshumanv** [comment]
Link?

**Comment by aashutoshrathi** [comment]
@samagragupta Link dedo franz.

**Comment by samagragupta** [comment]
@anshumanv @aashutoshrathi http://fretful-curve.surge.sh/

<blockquote><div><strong><a href="http://fretful-curve.surge.sh/">Cerebro 2019 - The Tech Fest</a></strong></div></blockquote>

**Comment by aashutoshrathi** [comment]
@samagragupta  Resolve conflicts ASAP.

**Comment by aashutoshrathi** [comment]
One more final surge link @samagragupta

**Review by anshumanv — APPROVED** [review]

**Pull request merged**
