### PR TITLE
Added brochure in popup pdf modal

### PR DESCRIPTION
**Pull request by samagragupta**

### CODE REVIEW

**Review by aashutoshrathi — CHANGES_REQUESTED** [review]
Are you sure about using token in the code base? and also something goes wrong with sign in button

**Comment by samagragupta** [comment]
@aashutoshrathi Netlify App is not authorized to sign in using google.

**Comment by samagragupta** [comment]
@aashutoshrathi Please review

**Comment by aashutoshrathi** [comment]
Add it in Mobile Nav too.

**Review by aashutoshrathi — CHANGES_REQUESTED** [review]
Check comments

**Comment by samagragupta** [comment]
@aashutoshrathi Done the changes.

**Review by rossoskull — COMMENTED** [review]
Just add some hover effects for the close icon, rest looks good

**Comment by samagragupta** [comment]
@rossoskull Done

**Comment by anshumanv** [comment]
image

Close button overlaps, also not white border/bg around the embed please.

**Comment by samagragupta** [comment]
@anshumanv Done the changes.

**Comment by aashutoshrathi** [comment]
Looks Better now

**Review by aashutoshrathi — APPROVED** [review]

**Pull request merged**
