### PR TITLE
Added pdf for timeline

### PR DESCRIPTION
**Pull request by samagragupta**
#68

### CODE REVIEW

**Review by anshumanv — CHANGES_REQUESTED** [review]
Fixed icon on the top right of the page below nav

**Comment by samagragupta** [comment]
@anshumanv Please review.

**Review by aashutoshrathi — CHANGES_REQUESTED** [review]
image

😕

**Comment by samagragupta** [comment]
@aashutoshrathi Please review

**Comment by anshumanv** [comment]
> Fixed icon on the top right of the page below nav

Use a download icon instead of text.

**Comment by samagragupta** [comment]
@anshumanv Done

**Review by aashutoshrathi — CHANGES_REQUESTED** [review]
- Button not properly aligned on Mobile
- Use better icon

**Comment by samagragupta** [comment]
@aashutoshrathi Done

**Review by aashutoshrathi — APPROVED** [review]
Looks better.
@anshumanv please merge

**Pull request merged**
