### PR TITLE
Add Sponsor logos in footer

### LINKED ISSUE #81: Add sponsors logos in footer

### PR DESCRIPTION
**Pull request by rossoskull**
Fixes #81

### CODE REVIEW

**Review by samagragupta — DISMISSED** [review]
Decrease the size of images.
spon

**Comment by aashutoshrathi** [comment]
Ye to bawaseer hai 😢

**Review by aashutoshrathi — CHANGES_REQUESTED** [review]
Please fix image sizes

**Comment by aashutoshrathi** [comment]
@rossoskull Please update this ASAP.

**Review by aashutoshrathi — APPROVED** [review]
LGTM

**Pull request merged**
