### PR TITLE
Dark cards

### LINKED ISSUE #34: Make white cards dark, with black shadow
screenshot from 2019-02-18 23-23-48
screenshot from 2019-02-18 23-25-03

### PR DESCRIPTION
**Pull request by rossoskull**
Fixes #34 
Preview link - https://subsequent-railway.surge.sh

### CODE REVIEW

**Comment by rossoskull** [comment]
You may not be able to login on this deployment, so this is how the profile card looks

screenshot from 2019-02-18 23-56-25

**Review by aashutoshrathi — CHANGES_REQUESTED** [review]
Reduce the space between name and mobile number and similarly in about card too. 
Rest looks ❤️ 

https://open.spotify.com/track/0qtkTBG3okPkM6zbr1YyLS 🎵

**Comment by aashutoshrathi** [comment]
Plus a bit of shadow won't harm.

**Comment by rossoskull** [comment]
I've added shadows below both the cards, But it isn't much apparent in the image

**Comment by rossoskull** [comment]
Preview link updated

**Review by aashutoshrathi — APPROVED** [review]
LGTM ✨ 
Let's wait for @anshumanv's final call and merge.
I'll deploy ASAP after merge.

**Comment by aashutoshrathi** [comment]
`yarn build && firebase deploy` ✔️

**Pull request merged**
