### PR TITLE
Added countdown

### PR DESCRIPTION
**Pull request by samagragupta**
#17

### CODE REVIEW

**Comment by samagragupta** [comment]
@aashutoshrathi @anshumanv Please review.

**Review by anshumanv — CHANGES_REQUESTED** [review]
image

Increase font size of numbers, colors to be aligned properly, I think we had some text last year like, "Starts in" or something, confirm with @aashutoshrathi

**Review by aashutoshrathi — CHANGES_REQUESTED** [review]
@samagragupta please follow whatever @anshumanv suggested ASAP.
PS: We are making the site for Cerebro 2019

**Comment by samagragupta** [comment]
@anshumanv Should I insert 'Starts in' text above the countdown?

**Comment by anshumanv** [comment]
Yes.

**Comment by samagragupta** [comment]
@anshumanv Done

**Comment by anshumanv** [comment]
✅

**Review by anshumanv — APPROVED** [review]
✅

**Pull request merged**
