### PR TITLE
Increased the font size of rules and contact

### LINKED ISSUE #58: Increase font size of Contact button in event section
capture

Same as of Rules heading

### PR DESCRIPTION
**Pull request by samagragupta**
Fixed #58

### CODE REVIEW

**Review by aashutoshrathi — CHANGES_REQUESTED** [review]
Weights are still different

**Comment by samagragupta** [comment]
@aashutoshrathi Made the weights similarly.

**Comment by rossoskull** [comment]
The event description font size is also increased. Should it be?

screenshot from 2019-02-24 10-06-41

**Comment by aashutoshrathi** [comment]
@rossoskull It shouldn't also try not using `!important`

**Comment by samagragupta** [comment]
@aashutoshrathi @rossoskull Review.

**Comment by aashutoshrathi** [comment]
@rossoskull Review and merge after conflicts are resolved.

**Review by rossoskull — APPROVED** [review]

**Pull request merged**
