### PR TITLE
Improve styling of Navbar

### PR DESCRIPTION
**Pull request by rossoskull**
Improved the styling of NavBar
Deployed preview : http://orange-creature.surge.sh/

### CODE REVIEW

**Review by aashutoshrathi — COMMENTED** [review]
Isn't it getting too much dull, plus please make sure you send PRs to dev

**Review by anshumanv — APPROVED** [review]
Updated opacity to 0.9 and font weight to 500, should be good I think. @PiyushPawar17

**Comment by rossoskull** [comment]
Updated preview link : https://festive-color.surge.sh
Thanks @anshumanv 

<blockquote><div><strong><a href="https://festive-color.surge.sh/">Cerebro 2019 - The Tech Fest</a></strong></div></blockquote>

**Comment by anshumanv** [comment]
@aashutoshrathi @PiyushPawar17 @DivyeshPuri  review and merge.

**Review by DivyeshPuri — COMMENTED** [review]
Navbar is not responsive.

**Review by aashutoshrathi — COMMENTED** [review]
- I would be thankful if you can shift from `px` to `rem`.
- Plus, I'm not sure who again changed it, but please remove `The Tech Fest` from the main page title.
- Create a drawer for small screens and similarly shift social icons to horizontal for small screens.

**Comment by rossoskull** [comment]
Preview link https://dusty-plate.surge.sh

<blockquote><div><strong><a href="https://dusty-plate.surge.sh/">Cerebro 2019 - The Tech Fest</a></strong></div></blockquote>

**Review by aashutoshrathi — APPROVED** [review]
Navbar looks good now. and it works for phones, can you make drawer dark too? Plus is there something wrong with logo.

screenshot from 2019-02-09 19-40-15

**Comment by rossoskull** [comment]
Improvements made @aashutoshrathi 
preview: https://large-ticket.surge.sh

The problem with the logo is in it's image file.

<blockquote><div><strong><a href="https://large-ticket.surge.sh/">Cerebro 2019 - The Tech Fest</a></strong></div></blockquote>

**Review by aashutoshrathi — COMMENTED** [review]
Nav is still bright, and there is a container behind it, which is not needed.
Can you fix that?
image

**Comment by rossoskull** [comment]
Preview link : https://real-chair.surge.sh

<blockquote><div><strong><a href="https://real-chair.surge.sh/">Cerebro 2019 - The Tech Fest</a></strong></div></blockquote>

**Review by samagragupta — CHANGES_REQUESTED** [review]
Please add a hover feature on social icons.
hover

**Comment by rossoskull** [comment]
preview link: http://venomous-fruit.surge.sh/

<blockquote><div><strong><a href="http://venomous-fruit.surge.sh/">Cerebro 2019 - The Tech Fest</a></strong></div></blockquote>

**Comment by aashutoshrathi** [comment]
Hovering still not working 😕

**Comment by rossoskull** [comment]
It's working for me :sweat_smile: 
Can you please check the new deployment link again?
http://venomous-fruit.surge.sh/

<blockquote><div><strong><a href="http://venomous-fruit.surge.sh/">Cerebro 2019 - The Tech Fest</a></strong></div></blockquote>

**Comment by anshumanv** [comment]
Update, Hovering on icons makes the cursor pointer, maybe scale them up too by some 1.2.

**Review by aashutoshrathi — COMMENTED** [review]
I thought there would be some kinda hovering effect. 😕

**Comment by rossoskull** [comment]
Preview link - http://fixed-tub.surge.sh/

<blockquote><div><strong><a href="http://fixed-tub.surge.sh/">Cerebro 2019 - The Tech Fest</a></strong></div></blockquote>

**Comment by rossoskull** [comment]
Preview link : http://abusive-hands.surge.sh/

<blockquote><div><strong><a href="http://abusive-hands.surge.sh/">Cerebro 2019 - The Tech Fest</a></strong></div></blockquote>

**Pull request merged**
