### PR TITLE
My Events component

### PR DESCRIPTION
**Pull request by rossoskull**
My Events component and link in the navbar
Preview link : http://exotic-marble.surge.sh/

### CODE REVIEW

**Review by anshumanv — COMMENTED** [review]
Have responsiveness issues, please fix.

@aashutoshrathi 😏

**Review by aashutoshrathi — CHANGES_REQUESTED** [review]
- Issues with responsiveness.
- Make `Registered events` smaller.
- Add round border and shadow to the card.
- And since Event Table is scrollable, use some good looking table component with a better scrollbar.
- In action use icons instead of text. (Use of [Eva Icons](https://akveo.github.io/eva-icons/#/) is recommended.
- Don't route to `myevents` instead use `my-events` or simply `dashboard` **(Open to discussions)**

**Comment by rossoskull** [comment]
>     * Don't route to `myevents` instead use `my-events` or simply `dashboard` **(Open to discuss)**
`dashboard` looks clean

**Comment by rossoskull** [comment]
Made the changes,
preview link - http://imminent-kick.surge.sh/

The trash can icon is used as an image, so color isn't changing. I used Eva icons as suggested by @aashutoshrathi. Should I go for font-awesome?

<blockquote><div><strong><a href="http://imminent-kick.surge.sh/">Cerebro 2019 - The Tech Fest</a></strong></div></blockquote>

**Comment by anshumanv** [comment]
Overlap prevent  🤔 
image

**Comment by aashutoshrathi** [comment]
@rossoskull Sure, switch to font awesome.

**Review by piyush-pawar-17 — CHANGES_REQUESTED** [review]
@rossoskull 
- Make the icons white.
- Decrease the font weight in input element of Mobile number.
- Add margin to top.
- Add margin between heading and the table.

**Comment by rossoskull** [comment]
> Overlap prevent thinking  

The social icons will become horizontal, so they won't be overlapped @anshumanv

**Review by aashutoshrathi — CHANGES_REQUESTED** [review]
New deployment link

**Comment by rossoskull** [comment]
Preview link - http://possible-event.surge.sh/

<blockquote><div><strong><a href="http://possible-event.surge.sh/">Cerebro 2019 - The Tech Fest</a></strong></div></blockquote>

**Review by aashutoshrathi — COMMENTED** [review]
Is this expected?

screenshot from 2019-02-09 19-41-52

**Comment by rossoskull** [comment]
Preview : https://scintillating-dogs.surge.sh

<blockquote><div><strong><a href="https://scintillating-dogs.surge.sh/">Cerebro 2019 - The Tech Fest</a></strong></div></blockquote>

**Review by aashutoshrathi — COMMENTED** [review]
- Make hover color for bin icon a bit lighter.
- Reduce padding around name and number.
image

**Comment by rossoskull** [comment]
Preview link : http://cagey-road.surge.sh/

<blockquote><div><strong><a href="http://cagey-road.surge.sh/">Cerebro 2019 - The Tech Fest</a></strong></div></blockquote>

**Review by samagragupta — CHANGES_REQUESTED** [review]
Facebook icon is overlapping
fb icon

**Comment by rossoskull** [comment]
@samagragupta I think it is being resolved in another PR I made :thinking:

**Review by aashutoshrathi — APPROVED** [review]
Looks good for now

**Pull request merged**
