### PR TITLE
Updated new timeline and data is retrieved from firebase

### PR DESCRIPTION
**Pull request by samagragupta**
Fixes : #43 #15 #42

### CODE REVIEW

**Review by rossoskull — CHANGES_REQUESTED** [review]
* Increase the font size in the event blocks
* Add a link from these blocks to their respective events
* Also fix the following-
screenshot from 2019-02-26 20-17-49

**Comment by samagragupta** [comment]
@rossoskull @aashutoshrathi @anshumanv Please review.

**Review by anshumanv — CHANGES_REQUESTED** [review]
Display loader while timeline is being fetched, time and event desc's size/color to be change so it's differentiable, see if you can get a better font too.

**Comment by samagragupta** [comment]
@anshumanv Done.

**Review by aashutoshrathi — APPROVED** [review]
Looks good, remove clg's in another PR

**Pull request merged**
